### ISSUE TITLE
First subplot axis='off' when extra_subplots=0

### ISSUE THREAD

**Issue by r-b-g-b** [yhat/ggplot#132]
When ```facet_wrap``` generates more subplots than I need, the code smartly makes the unused axes invisible. However, when I make exactly as many subplots as I need, the first subplot has its axis turned off. I think the error originates from ```Line 145``` in ```ggplot.py```:
```
for extra_plot in axs.flatten()[-extra_subplots:]:
    extra_plot.axis('off')
```
When ```extra_subplots>0```, this works (i.e. ```axs.flatten()[-2:]``` turns off the axes of the last two plots), but when ```extra_subplots==0```, ```axs.flatten()[0:]``` turns off the axes for all of the subplots. Strangely enough, the final figure has all of the ```axis='on'``` except for the first. It looks like when the axes are being looped over for plotting, this line (```Line 245``` for facet_wrap)
```
plt.subplot(self.n_wide, self.n_high, pos)
```
causes new axes to be drawn on all but the first subplot. I really don't know why this is, but I'm guessing it's a decision on the matplotlib side. Any thoughts?

In any case, adding a condition (before ```Line 145```)
```
if extra_subplots>0:
    for extra_plot in axs.flatten()[-extra_subplots:]:
        extra_plot.axis('off')
```
seems to fix the problem.

**Comment by glamp** [comment]
fixed in 0.9.3
