### ISSUE TITLE
Plot numpy arrays

### ISSUE THREAD

**Issue by kevindavenport** [yhat/ggplot#141]
It would be great if we could reduce the overhead of having to convert large numpy arrays into dataframes just to do a simple plot. Forgive me if there is already a way to do this, I searched but could not find documentation around it and there isn't a py-ggplot message board.

Thank you!

**Comment by glamp** [comment]
qplot

**Comment by kevindavenport** [comment]
Yessss

**Comment by glamp** [comment]
And now the docs...

http://yhat.github.io/ggplot/notebook.html?page=build/docs/plotting/qplot.html

![](http://i.giphy.com/l0O7P6qdCa1AKJRAY.gif)
