### ISSUE TITLE
Dimensions reversed for facets

### ISSUE THREAD

**Issue by d10genes** [yhat/ggplot#182]
When calling `p + g.geom_point() + g.facet_wrap(x='Var', ncol=6)`, I get 6 rows, not 6 columns.

I believe this can be traced to [`ggplot.py` line 165](https://github.com/yhat/ggplot/blob/master/ggplot/ggplot.py#L165) (`plt.subplot(self.n_wide, self.n_high, 1)`). The [signature for `subplot`](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.subplot) is `subplot(nrows, ncols, plot_number)` so I think the line should read `plt.subplot(self.n_high, self.n_wide, 1)`. There may be some more lines that need to be fixed.

**Comment by glamp** [comment]
fixed in 0.9.3
