### ISSUE TITLE
Wrong Unittests

### ISSUE THREAD

**Issue by janschulz** [yhat/ggplot#199]
Doing some refactoring work for #188 brought up some interesting "bad" unittests: I changed the tranformation and get_layer code so that it errors if a mapping in aes is used to set a value. From my POW, thats wrong as one can see from the below differences between ggplot2 and our current implementation:

from ggplot.tests.test_basic.test_alpha_density, which now fails
```
def test_alpha_density():
    gg = ggplot(aes(x='mpg', fill=True, alpha=0.3), data=mtcars)
    assert_same_ggplot(gg + geom_density(), "geom_density_alpha")
```
![geom_density_alpha](https://f.cloud.github.com/assets/890156/2104159/79b9f036-8f77-11e3-8f9b-dbc070343993.png)

vs ggplot2:
```
library(ggplot2)
gg = ggplot(aes(x=mpg, fill=TRUE, alpha=0.3), data=mtcars)
gg + geom_density()
```

![rplot](https://f.cloud.github.com/assets/890156/2104167/a7dd84fa-8f77-11e3-8d7a-a0f18e8abca1.png)

**Comment by glamp** [comment]
no longer relevant
