### ISSUE TITLE
geom_hline, geom_vline has wrong aes

### ISSUE THREAD

**Issue by janschulz** [yhat/ggplot#203]
According to http://docs.ggplot2.org/0.9.3.1/geom_hline.html / http://docs.ggplot2.org/0.9.3.1/geom_vline.html instead of `y` `yintercept` is used. (of x and `xintercept` for vline) 

The ggplot2 commands also do not understand 'y/xmin' or 'y/xmax'...

Also there is a bug in the current code: if no 'y'/'x' mappingis given, `y` or `x` is not assigned a value and an "variable used before assignment' us thrown. There should be a guard against this.

**Comment by glamp** [comment]
fixed in 0.9.3
