### ISSUE TITLE
scale_colour_manual doesn't do anything

### ISSUE THREAD

**Issue by naught101** [yhat/ggplot#215]
This should produce a scatterplot with 4 groups of 

    df = pandas.DataFrame({'x': rand(40), 'y': rand(40), 'c': 10*[1,2,3,4]})
    gg.ggplot(df, gg.aes('x', 'y', colour='c')) + geom_point() + scale_colour_manual(['#FF0000', '#0000FF', '#00FF00', '#AAAA00'])

Should produce a scatter graph with four colours (red, blue, green, and orange). Instead, it produces a scatter with the standard white/blue gradient.

**Comment by makmanalp** [comment]
This is super frustrating to me too, that values isn't just the default argument - I've spent half an hour tracking why it wasn't working. According to the docs that's the only thing a user will pass in, so why not just set it as the default argument?

Digging in, looks like scale_color_manual inherits from scale and thus also inherits the default behavior of `self.name = args[0]`: https://github.com/yhat/ggplot/blob/master/ggplot/scales/scale.py#L11

Maybe defining a custom constructor is a good idea. https://github.com/yhat/ggplot/blob/master/ggplot/scales/scale_colour_manual.py#L13

Also the link for scale_color_manual in the docs is broken: http://ggplot.yhathq.com/docs/index.html

Should be: ggplot.yhathq.com/docs/scale_colour_manual.html

**Comment by glamp** [comment]
fixed

**Comment by makmanalp** [comment]
@glamp on a roll!  👍 🎉 🎈
