### ISSUE TITLE
No colourbar when faceting

### ISSUE THREAD

**Issue by naught101** [yhat/ggplot#236]
Both of the following plots are generated with this code:
```
ggplot(iris, aes(x=Sepal.Length, y=Petal.Length, colour=Petal.Width)) + geom_point() + facet_wrap('Species')
```

(The iris dataset exported from R and imported using pandas, no tweaking necessary. Very nice!)

There is no colour bar in the python version. 

R ggplot:

![iris_r](https://f.cloud.github.com/assets/167164/2328049/b92618dc-a3f7-11e3-9c5d-eb9e3d13d066.png)

Python ggplot:

![iris_python](https://f.cloud.github.com/assets/167164/2328050/b92944da-a3f7-11e3-8c15-3f1f7aca8be5.png)

**Comment by glamp** [comment]
see 0.9.3
