### ISSUE TITLE
Add "pd.set_option('mode.chained_assignment','warn')" in all tests

### ISSUE THREAD

**Issue by janschulz** [yhat/ggplot#238]
pandas/numpy has a funky thing called views which keeps memory usage down but also means that in some cases a assignment to a pandas dataframe will also change something in the old frame from which this dataframe came from or (the reverse case) a change/assignment to a dataframe will not actually be done to the frame but to a copy. For the last case pandas introduced the above option and this option should be enabled in all tests so that cases where we do such a thing will fail the testsuite and not result in weird errors later on.

As I've seen such an error once during a ggplot test run I'm not sure f we already have such cases in the code.

Generally all double slicing + assignments (which should go to the original frame) should be avoided: `df["col"]["row"] = ...`. Also in all cases where ggplot does a slicing operation and wants to update the slice but not the original frame, a `df_slice = df_slice.copy()` should  be used. 

The copy problem will probably turn up (or better "needs to be taken care of") in #221...

See http://stackoverflow.com/questions/21463589/pandas-chained-assignments/21463854#21463854 and http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

**Comment by glamp** [comment]
fixed
