### ISSUE TITLE
Cannot Color by Boolean Column

### ISSUE THREAD

**Issue by zachcp** [yhat/ggplot#244]
I was working on a simple plot example where I wanted to color by a boolean column. The resulting legend defaulted to five color gradients instead of two. Ive attempted to recreate the example with the diamonds dataset but have been churning through this example for several minutes.  It works by truncating the dataframe to only afew record as below (see picture below)

```
from ggplot import *

def isideal(cut):
    if cut == "Ideal":
        return True
    else:
        return False

df = diamonds    
df['isideal'] = df.cut.apply(isideal)
df = df[:10]
ggplot(aes(x='depth', y='price', colour='isideal'), data=df) + geom_point()
 
```

![image](https://f.cloud.github.com/assets/1260667/2387342/f0ad026e-a935-11e3-81a3-ed956aaf79fc.png)

**Comment by glamp** [comment]
fixed
