### ISSUE TITLE
facet_wrap puts axes labels in weird places

### ISSUE THREAD

**Issue by porterjamesj** [yhat/ggplot#245]
As pictured:

![image](https://f.cloud.github.com/assets/2532521/2391669/b2ca3f52-a96c-11e3-9e5c-3705646dd1b9.png)

The command used to produce this was :

```python
ggplot(res, aes(y="error",x="gamma")) + geom_point() + stat_smooth() + facet_wrap("C")
```

and I can provide the dataframe if necessary.

also thank you all for making this package :) glad that I can plot declaratively in python now.

**Comment by glamp** [comment]
fixed in 0.9.3
