### ISSUE TITLE
geom_point can't have more than 8 colors

### ISSUE THREAD

**Issue by catethos** [yhat/ggplot#251]
Consider the following code, the data should have 10 categories, ie: "a" to "j". And I would like to color the points according to their categories, however the categories "a" and "b" are missing from the plot.

```python
l = ["a","b","c","d","e","f","g","h","i","j"]
df = pd.DataFrame({"x":randn(100),"y":randn(100),"c":repeat(l,10)})
p = ggplot(aes(x="x",y="y",color="c"),data=df) + geom_point()
p
```
![image](https://f.cloud.github.com/assets/6882603/2428638/29b7b678-ac54-11e3-9b3d-3db77aecd7f3.png)

**Comment by glamp** [comment]
fixed in 0.9.3
