### ISSUE TITLE
scale_x_date is not applied to all charts

### ISSUE THREAD

**Issue by felixgao** [yhat/ggplot#260]
![image](https://cloud.githubusercontent.com/assets/1153820/2574370/fc713aec-b930-11e3-93d0-43e5349212b5.png)

the data looks like the following 
         d              cat    value
0  2014-03-01   17  3311150
1  2014-03-02   17  3768941
2  2014-03-03   17  3272166
3  2014-03-04   17  2148346
4  2014-03-05   17  2573568
5  2014-03-06   17  2294264
6  2014-03-07   17  2042997
7  2014-03-08   17  2086284
8  2014-03-09   17  1660929
9  2014-03-10   17  2212416

notice the first column and third row's x axis is not the right date as the second column third row.

**Comment by glamp** [comment]
fixed in 0.9.3
