### ISSUE TITLE
Proper scales

### ISSUE THREAD

**Issue by has2k1** [yhat/ggplot#283]
Currently, the scales that are present are just holders for settings passed onto the ggplot object at `__radd__` time. The scales need to be more complete with knowledge of the data domain and the functions to map the domain onto the aesthetic range, i.e. the current `assign_*` functions need to be refactored into the scales.

The scales should be added to the ggplot object and should remain separate objects until plot time e.g under `ggplot.scales`. Also, only the ggplot scales should know about the transformations, the matplotlib scales available through `ax` should know nothing.

All this is key for among other things, a straight forward facetting implementation and statistic computations. Scale trainning will also be easy this way, since it needs to be done to avoid a bunch of edge cases. e.g. `geom_text` and [`geom_bar`](https://github.com/yhat/ggplot/issues/196)

**Comment by makmanalp** [comment]
Possibly #248

**Comment by has2k1** [comment]
I think the problem(s) may be coming from more than one source. In the plot building pipeline there isn't a clear distinction of what should be handled by ggplot and what is handled by matplotlib. The best solution is to fix the underlying architecture to adhere to the same process as ggplot2. This is what I am trying to do in #360, it is big (almost a complete rewrite) and I haven't made any commits lately.

**Comment by makmanalp** [comment]
@has2k1 no worries, not trying to pressure you, just trying to tie bugs together and investigate further so if/when you tackle this you'll have less hunting to do.

One thing I'd appreciate is where I'd start looking if I wanted to fix the outputs manually - like, after the matplotlib elements are generated, where / how would I intercept them before they get repr()'d so I can, say, manually fix the viewport or investigate what's going on?

**Comment by has2k1** [comment]
@makmanalp, that would have to be in the `ggplot/ggplot.py` [draw](https://github.com/yhat/ggplot/blob/0f3774e6a645796b843d3ce77fb388958773338e/ggplot/ggplot.py#L135) method. There is a lot going on in there and it is a very unsightly. Maybe try poking around after the log scales are [applied] (https://github.com/yhat/ggplot/blob/0f3774e6a645796b843d3ce77fb388958773338e/ggplot/ggplot.py#L135).

**Comment by makmanalp** [comment]
@has2k1 Perfect, thank you so much.
