### ISSUE TITLE
Refactor geom plot functions to be class/static methods.

### ISSUE THREAD

**Issue by has2k1** [yhat/ggplot#292]
With the stats and geoms separated (PR #266), the rationale for such a change has become more apparent.

**Support**
- The plot functions do not need the access to the `geom` instance and so far no need for the class.

- Some of the current plotting methods carry heavy performance penalties. e.g `axes.bar` which is used for `geom_bar`/`geom_histogram` and `geom_rect`. `axes.bar` uses a separate `patch` (and therefore a separate `artist`)  for each bar/rectangle. For this particular case we can get upto x10(my timings) performance boost by using `collections.PolygonCollection`. With potential optimisations to key plotting functions, it make sense to  reuse them instead of duplicating the efforts. As such, a `geom_boxplot` implementation would use plot funcitons of `geom_point`, `geom_vline` and `geom_rect` (when notch=False). We can be also be specific and use collection functions that do not autoscale, this would give us full control of the scaling for the viewport.

- It vibes with ggplot2.

**Against**
- It seems like(from the changelogs) matplotlib makes use of most chances to optimize collections to get them to handle every parameter that does not require a different `artist`. So there may be incompatibilities between versions at the collection level, a higher level function that is less efficient.

**Related stuff**
- When stats do computations they, the create aesthetics or values that are as general as possible, e.g. `stat_bin` creates `x`, `y` and `width`, instead of `xmin`, `xmax`, `ymin` and `ymax`. As a result more `geoms` e.g. `geom_point` can use `stat_bin`. This is the reason for a potential re-parameterisation step. It allows the plotting methods to only do the plotting. This would be key to reusable class/static methods.

- To control the scaling of the view port, it would probably be better to do this after issue #283 has been resolved.

**Comment by glamp** [comment]
nope
