### ISSUE TITLE
Facet Wrap loses all axis formatting

### ISSUE THREAD

**Issue by BlackArbsCEO** [yhat/ggplot#295]
When trying to plot stock time series using facet_wrap I found bugs with the axis formatting involving the dates (either showing for 1/4 charts, or losing the datetime format) and the x axis losing the percent formatting. Reproducible code is below: 

import datetime
from ggplot import *
import pandas.io.data as web
import pandas as pd
import numpy as np

 # DATES #

 # annl
A0 = datetime.datetime(2010,2,9)
A1 = datetime.datetime(2011,2,4)
A2 = datetime.datetime(2012,2,3)
A3 = datetime.datetime(2013,2,5)
A4 = datetime.datetime(2014,2,6)

stocks = ['BIIB'] 

#RETURN PANEL DATA # 
    #annl
sy1 = web.DataReader(stocks, 'yahoo', A0, A1)['Adj Close']
sy2 = web.DataReader(stocks, 'yahoo', A1, A2)['Adj Close']
sy3 = web.DataReader(stocks, 'yahoo', A2, A3)['Adj Close']
sy4 = web.DataReader(stocks, 'yahoo', A3, A4)['Adj Close']

 #Calc Return Data#
returns_sy1 = sy1.pct_change().dropna()
returns_sy1 = returns_sy1.apply(cumsum)
rt = returns_sy1.index
returns_sy1['Date'] = rt
returns_sy1.columns= ['BIIB_ANL PERF_1','Date']
returns_sy1.reset_index(drop=True)

returns_sy2 = sy2.pct_change().dropna()
returns_sy2 = returns_sy2.apply(cumsum)
rt = returns_sy2.index
returns_sy2['Date'] = rt
returns_sy2.columns= ['BIIB_ANL PERF_2','Date']
returns_sy2.reset_index(drop=True)

returns_sy3 = sy3.pct_change().dropna()
returns_sy3 = returns_sy3.apply(cumsum)
rt = returns_sy3.index
returns_sy3['Date'] = rt
returns_sy3.columns= ['BIIB_ANL PERF_3','Date']
returns_sy3.reset_index(drop=True)

returns_sy4 = sy4.pct_change().dropna()
returns_sy4 = returns_sy4.apply(cumsum)
rt = returns_sy4.index
returns_sy4['Date'] = rt
returns_sy4.columns= ['BIIB_ANL PERF_4','Date']
returns_sy4.reset_index(drop=True)

 # format data for ggplot # 
dflist = [returns_sy1,returns_sy2,returns_sy3,returns_sy4]
masterFrame = pd.concat(dflist)

 # Plot code # 
ret_all = pd.melt(masterFrame, id_vars='Date')
rx_all = ret_all.rename(columns = {'Date':'Date','variable':'Stock Period','value':'Returns'})

perfChart = ggplot(aes(x='Date', y='Returns', color='Stock Period'),data=rx_all) \
+geom_line() \
+scale_x_date(breaks=date_breaks('1 month'), labels='%b %Y') \
+scale_y_continuous(labels='percent')

perfChart + facet_wrap('Stock Period') 

![facet_wrap_error](https://cloud.githubusercontent.com/assets/7452471/2845858/4620a994-d09b-11e3-8db4-a9b0099438e0.png)

**Comment by glamp** [comment]
fixed
