### ISSUE TITLE
no "group"  aes in the refactored geom_line() 

### ISSUE THREAD

**Issue by zachcp** [yhat/ggplot#302]
I was running into an issue with groups similar to #87, which was fixed was fixed in #98. However, it looks like the code in master no longer has `group` as a valid `aes`. Any chance we can fix that?

For reference the following code generates the attached image which is incorrect (see #87 ) for reference

```
data = [{"gender": "m", "y": 30, "x": 10}, {"gender": "m", "y": 48, "x": 20}, {"gender": "f", "y": 20, "x": 10}, {"gender": "f", "y": 12, "x": 20}]
df = DataFrame(data)
print ggplot(df, aes(x='x', y='y', group="gender")) + geom_line() 
```

![image](https://cloud.githubusercontent.com/assets/1260667/2973338/d9b46c54-db7c-11e3-9825-d0ae14f3d5cb.png)

**Comment by glamp** [comment]
fixed in 0.9.3
