### ISSUE TITLE
geom_histogram() + scale_y_log() doesn't appear to work

### ISSUE THREAD

**Issue by gallamine** [yhat/ggplot#306]
I'm trying to show a histogram with a logarithmic y axis. When I chain `geom_histogram()`with `scale_y_log()` the graph doesn't show any data. Perhaps it's because the plot aesthetics don't contain a `y` value?

An example:

```
import ggplot as gg
import pandas as pd
import numpy as np
df = pd.DataFrame({"x": np.random.randn(100)})
p = gg.ggplot(gg.aes(x='x'), data = df) + gg.geom_histogram() + gg.scale_y_log()
p
```

![image](https://cloud.githubusercontent.com/assets/777088/3045661/a61daea2-e11f-11e3-9bbd-0e473272eef1.png)

**Comment by glamp** [comment]
fixed
