### ISSUE TITLE
Change project name?

### ISSUE THREAD

**Issue by tlnagy** [yhat/ggplot#330]
I'm a big fan of the work here to port ggplot2 to python, but it is almost impossible to find documentation for this library in the noise caused by the R version. Now, I know that one of the project's goals is to preserve the syntax of the R implementation, but there will always be nuances stemming from the different bases of the two projects. Therefore, it would be nice to have a more differentiable name so that potential users can find these nuances: e.g. pyggplot. 

Just a suggestion.

**Comment by naught101** [comment]
ggplot is nice and clean - it's clear what it is (grammar of graphics plotting - what the hell is the 2 for anyway?). Ideally, most R ggplot2 help requests will also be relevant for this ggplot anyway, and if not, that's probably a bug, right? I vote for leaving it as it is.

**Comment by glamp** [comment]
not changing the name
