### ISSUE TITLE
Color legend mismatch using 3-point gradient

### ISSUE THREAD

**Issue by IamJeffG** [yhat/ggplot#364]
When I set a 3-point color ramp using  `scale_color_gradient` or `scale_color_gradient2`, the color legend shows only the "low" to "mid" colors as being the limits of the range.  As a result the color->value map shown in the legend is not only incomplete, it also doesn't match the values actually shown in the plot.

    p = ggplot(diamonds, aes(x='depth', y='carat', colour='price')) +  geom_point()
    print(p + scale_colour_gradient2(low='blue', mid='white', high='red'))

Defining a 2-point color ramp with these functions seems to work correctly.

**Comment by glamp** [comment]
fixed
