### ISSUE TITLE
facet_grid all fail if one facet fails - ValueError: ordinal must be >= 1>

### ISSUE THREAD

**Issue by andaag** [yhat/ggplot#367]
Hi

I'm getting this fairly often with facet_grid. It seems to be because some of the facets have too few datapoints. I can filter for that, but it's a quite annoying extra step. Especially as my data changes, I've seen this pop up every now and again, and find myself filtering pretty much all the data where I'm using facet_grid.

Any chance of allowing facet_grid to not fail catastrophically rendering all plots when one of them fail?

**Comment by glamp** [comment]
fixed in 0.9.3
