### ISSUE TITLE
facet_grid failing with just the y parameter

### ISSUE THREAD

**Issue by galli-a** [yhat/ggplot#375]
I see a similar issue to #183. However, with only the `x` parameter the `facet_grid` command works, although with a vertical instead of horizontal layout, as stated in #182. Oh the other hand, with just the `y` parameter, the command fails with an error:

    AttributeError: 'NoneType' object has no attribute 'unique'

ggplot version is 0.6.5. Tested on both Windows and OS X, with both Python 2.7 and 3.4, and both console and IPython Notebook.
A reproducible example is:

    import pandas as pd
    import numpy as np
    import matplotlib.pyplot as plt
    from ggplot import *
    
    column1 = np.random.randint(1, 21, 100)
    column2 = np.random.randint(1, 21, 100)
    column3 = np.random.randint(1, 6, 100)
    column4 = np.random.randint(1, 6, 100)
    data = list(zip(column1, column2, column3, column4))
    data_raw = pd.DataFrame(data = data, columns = ['a', 'b', 'c', 'd'])
    
    p1 = ggplot(data_raw, aes(x = 'a', y = 'b')) + geom_line()
    p1 = p1 + facet_grid(x = 'c', y = 'd')
    print(p1)
    
    p2 = ggplot(data_raw, aes(x = 'a', y = 'b', color = 'c')) + geom_line()
    p2 = p2 + facet_grid(x = 'd')
    print(p2)
    
    p3 = ggplot(data_raw, aes(x = 'a', y = 'b', color = 'c')) + geom_line()
    p3 = p3 + facet_grid(y = 'd')
    print(p3)

**Comment by glamp** [comment]
fixed in 0.9.3
