### ISSUE TITLE
No Legends Visible

### ISSUE THREAD

**Issue by johnny555** [yhat/ggplot#376]
Hi,

Whenever I plot I do not get legends. This is easily demonstrated using the diamonds example.

`from ggplot import *`
`print (ggplot(diamonds, aes(x='price', color='cut')) + \`
`geom_density())`

![diamonds](https://cloud.githubusercontent.com/assets/9003096/4500362/b0bb2e04-4a90-11e4-963e-0c7048d4e598.png)

I'm using ggplot 0.6.6 on ubuntu 14.04. Running from the command line.

I don't think this is the same as #33 as I'm not using ipython notebook.

Thanks.

**Comment by manugarri** [comment]
same here :/

**Comment by spicasax** [comment]
missing for me as well with ggplot (0.6.5)

**Comment by ledmonster** [comment]
I had same issue with ggplot 0.6.5. master branch also didn't work for me.

**Comment by sergii-bondariev** [comment]
I installed the latest version (0.6.6) as ecerulm wrote and the legend is now visible.

**Comment by mattayes** [comment]
Couldn't see the legend under v0.6.5. Installed v0.6.6 via @ecerulm's method. Can now see legends.
OS: Mac OSX v10.10.3
Python 3.4.3

**Comment by johnny555** [comment]
closed as the legends are now visible, however @skycaptain perhaps you should lodge a new issue to address that problem?

**Comment by mattayes** [comment]
@johnny555 the issue isn't totally fixed until v0.6.6 is on PyPi.

**Comment by drabbit17** [comment]
After having followed @ecerulm's method and having ggplot 0.6.6 correctly installed i still cannot see the legend when using facet_wrap.

OS: Mac OSX v10.10.3
Python 2.7.10

**Comment by fissehab** [comment]
I tried everything I can, but legend does not show. Any suggestion?

**Comment by sergii-bondariev** [comment]
use R/RStudio to make your plots with ggplot.
Or use matplotlib in python.

**Comment by skycaptain** [comment]
@johnny555, @sergii-bondariev: I moved to pandas and pure matplotlib. Sry, but I needed a more stabile lib.

**Comment by fissehab** [comment]
To use R and Python in Jupyter , I believe working with ggplot and ggplot2 for Python and R, respectively, seems more convenient specially for people coming from R and ggplot2. Hope the problem with ggplot will be fixed soon.
