### ISSUE TITLE
Time on X axis renders incorrectly the second time

### ISSUE THREAD

**Issue by jml** [yhat/ggplot#381]
When rendering a plot with time on the x axis and something else on the y, ggplot renders it perfectly the first time, but the second & subsequent times seems to reset the timestamps to near 1970 and completely mess up the ordering.

Once this behaviour is triggered, it's continued until the Python process is restarted.

I've verified this behaviour w/ matplotlib 1.4.2, ggplot 0.6.5, and pandas 0.13.1 on Mac OS X 10.9.

## Reproducing example

```python
from datetime import datetime, timedelta

from ggplot import *
import pandas as pd

dates = [datetime.now() + timedelta(days=i) for i in range(10)]
df = pd.DataFrame({'t': dates, 'x': range(10)})

ggplot(aes(x='t', y='x'), df) + geom_line()
ggplot(aes(x='t', y='x'), df) + geom_line()
```

## First time (correct)

![screen shot 2014-10-24 at 18 06 20](https://cloud.githubusercontent.com/assets/125674/4773237/3070ef92-5ba0-11e4-8462-d09e24b057a4.png)

## Second time (incorrect)

![screen shot 2014-10-24 at 18 06 34](https://cloud.githubusercontent.com/assets/125674/4773242/3a2e344a-5ba0-11e4-86d8-61bd7d1bf015.png)

**Comment by glamp** [comment]
0.9.3
