### ISSUE TITLE
Colour not working with geom_text

### ISSUE THREAD

**Issue by ghost** [yhat/ggplot#387]
from  ggplot import *
import pandas as pd
from pandas.compat import StringIO
sinput = """time          x          y
0     0 -13.533028 -21.433420
1     3  29.471418  22.191618
2     6   7.682483 -34.830922
3     9  24.615860  -1.341722
4    12 -21.152946  16.175614
5    18   5.194836   8.531450
6    21 -32.278623  10.707380"""
df = pd.read_csv(StringIO(sinput), sep=" ")
ggplot(aes(x="x", y="y", label="time"), data=df) + geom_text() # works
ggplot(aes(x="x", y="y", label="time", colour="factor(time)"), data=df) + geom_text() # does not work

![pca_plot_right](https://cloud.githubusercontent.com/assets/5526486/5121221/ab3c35e8-708f-11e4-97e7-9f750a1b5f48.png)
![pca_plot_wrong](https://cloud.githubusercontent.com/assets/5526486/5121222/ab3fa156-708f-11e4-956a-5bfe39f76f6c.png)

**Comment by glamp** [comment]
fixed in 0.9.3
