### ISSUE TITLE
theme_xkcd() -- Frozen error()

### ISSUE THREAD

**Issue by ilivni** [yhat/ggplot#389]
Hi - When plotting a `geom_line() ` using `theme_xkcd()` - I receive the following error:

`<repr(<ggplot.ggplot.ggplot at 0xd21d4e0>) failed: NotImplementedError: TransformNode instances can not be copied. Consider using frozen() instead.> `

This error does not happen with any other theme in ggplot

Working on:
1. Win 7 (64)
2. ipython (2.3)
3. Anaconda

**Comment by ncsaba** [comment]
I've got the same error when using the theme_xkcd() in ggplot (which under the hood uses matplotlib). There is an attempt in theme_xkcd to catch that exception and just skip copying the TransformNodes - but I still get the exception from another part of the code, so I ended up doing:

# monkey patching TransformNode:
def self_copy(self, *args, **kwargs):
    return self
TransformNode.__deepcopy__ = self_copy

For all those who seek for a quick workaround, that should work (it did work for me).

**Comment by glamp** [comment]
fixed in 0.9.3
