### ISSUE TITLE
bug in geom_tile

### ISSUE THREAD

**Issue by ernestrc** [yhat/ggplot#391]
Straight from http://blog.yhathq.com/posts/ggplot-0.4-released.html :
` df = pd.DataFrame({
    'x': ['a', 'b', 'c', 'a'],
    'y': [3, 2, 1, 2],
    'fill': np.random.random(4) }`
`print ggplot(aes(x='x', y='y', fill='fill'), data=df) +
    geom_tile() +
    xlab('X Label') +
    ylab('Y Label') +
    ggtitle('This is geom_tile!\n')`

Throws:
` File "/Library/Python/2.7/site-packages/ggplot/geoms/geom_tile.py", line 22, in _plot_unit
    fill = pinfo.pop('fill')
KeyError: u'fill'`

**Comment by ZoeLiu** [comment]
I got the same issue

**Comment by glamp** [comment]
fixed in 0.9.3

**Comment by adamboche** [comment]
```
import pandas as pd
import numpy as np
from ggplot import ggplot, aes, geom_tile, xlab, ylab, ggtitle
df = pd.DataFrame({'x': ['a', 'b', 'c', 'a'], 'y': [
                  3, 2, 1, 2], 'fill': np.random.random(4)})
ggplot(aes(x='x', y='y', fill='fill'), data=df) + geom_tile() + \
    xlab('X Label') + ylab('Y Label') + ggtitle('This is geom_tile!\n')

```

raises `TypeError: can't multiply sequence by non-int of type 'float'`

**Comment by alecuba16** [comment]
I have the same problem as @adamboche , there is a workarround?

**Comment by thomascjohnson** [comment]
Same issue for me. It sees that it can't handle categorical data, unless someone has a counter-example?

**Comment by conradbm** [comment]
Same issue. x and y are indeed categorical though, so it seems to bust whether or not it is categorical.

ggplot(aes(x='from', y='variable', fill = 'value'), data=covar_melted) + geom_tile()

TypeError: can't multiply sequence by non-int of type 'float'

**Comment by naught101** [comment]
@adamboche's bug is completely different to the original bug reported by @ernestrc. File a new bug if it's still happening.
