### ISSUE TITLE
scale_y_continuous label issue

### ISSUE THREAD

**Issue by ZoeLiu** [yhat/ggplot#397]
I tried to use the following code to label the ticks in y axis however I got an error msg "TypeError: unhashable type: 'list'"
scale_y_continuous(breaks=range(0,800000,100000), labels=["0K","100K","200K","300K","400K","500K","600K","700K","800K"]) 

By looking at the source code here: https://github.com/yhat/ggplot/blob/master/ggplot/scales/scale_y_continuous.py

It looks like the code is checking if the list exists in the dictionary using
if self.labels in LABEL_FORMATS

LABEL_FORMATS = {
    'comma': comma,
    'dollar': dollar,
    'currency': currency,
    'millions': millions,
    'percent': percent
}

So this means that adding a customized label is not even possible... however there's an example here that illustrate it should work: http://blog.yhathq.com/posts/ggplot-for-python.html

from ggplot import *

print ggplot(mtcars, aes('mpg', 'qsec')) + \
  geom_point(colour='steelblue') + \
  scale_x_continuous(breaks=[10,20,30],  \
                     labels=["horrible", "ok", "awesome"])

**Comment by eshilts** [comment]
I ran into this same issue.

Your example works because it is for `scale_x_continuous` and `scale_x_continuous` and `scale_y_continuous` have different implementations. 

Ideally the two methods would work similarly. One approach is to add a check to see if the labels are hashable as described [here](http://stackoverflow.com/a/3460747/599139).

**Comment by has2k1** [comment]
The current scales were implemented with out strict adherence to ggplot2, this will change in the future and this issue should then be gone.

**Comment by freeseek** [comment]
I have a similar issue. The following code works:

import ggplot, pandas
df = pandas.DataFrame({'x': [0,1],'y': [1,2]})
ggplot.ggplot(df, ggplot.aes(x = 'x', y = 'y')) + \
  ggplot.geom_point() + \
  ggplot.scale_x_continuous(labels = [])

But the following code:

import ggplot, pandas
df = pandas.DataFrame({'x': [0,1],'y': [1,2]})
ggplot.ggplot(df, ggplot.aes(x = 'x', y = 'y')) + \
  ggplot.geom_point() + \
  ggplot.scale_y_continuous(labels = [])

Gives the error:

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/genovese/.local/lib/python3.4/site-packages/ggplot/scales/scale_y_continuous.py", line 28, in __radd__
    if self.labels in LABEL_FORMATS:
TypeError: unhashable type: 'list'

**Comment by edoardovivo** [comment]
I am experiencing the same issue with a facet plot. I simply wanted all the y scales to look the same and within the same range. It seems to be not possible using scale_y_continuous. 

I tried with scale_y_discrete, and in that case I was able to set the ticks but not the limits.

**Comment by danteorta** [comment]
I had the same issue. Aa @edoardovivo said, I tried scale_y_discrete to be able to set the ticks. However I added the ylim() component to my plot to make it work. 

My code is the following:

p = ggplot(aes(x='m2construidos',y='preciom2'), data=aa) + \
geom_point(color='#0070C0', size=25, alpha=0.4) + xlim(20,lims_rec[recamaras]) +\
stat_smooth(color='gray', size=1.5, alpha=0.3, fill='steelblue') +\
facet_wrap('zona', scales='fixed') + xlab('') + ylab('') +\
scale_x_continuous(breaks=range(20,lims_rec[recamaras],20), labels=range(20,lims_rec[recamaras],20)) +\
scale_y_discrete(breaks=[20, 40, 60, 80], labels=['20k', '40k', '60k', '80k']) + ylim(0, 60)

**Comment by glamp** [comment]
fixed
