### ISSUE TITLE
multi variable plot doesnt render correcly

### ISSUE THREAD

**Issue by enpassanty** [yhat/ggplot#399]
OSX 10.9.5, Python 2.7.9 |Anaconda 2.1.0 (x86_64)| on Spyder, yhat-ggplot 0.6.5

I am tryingto plot the following data set:
'lng'  is a pandas dataframe:

   &nbsp;&nbsp;&nbsp;    date  &nbsp;&nbsp;  variable &nbsp;&nbsp;&nbsp; value
0  2013-04-01    xirrA -0.201173
1  2013-04-01    xirrB -0.212567
2  2013-04-01    xirrC -0.187462
3  2013-04-01    xirrE -0.270094
4  2013-04-01    xirrD -0.199426
5  2013-04-01    xirrG -0.197393
6  2013-04-01    xirrF -0.310290
7  2013-05-01    xirrF -0.277342
8  2013-05-01    xirrG -0.173624
9  2013-05-01    xirrC -0.165509
10 2013-05-01    xirrB -0.185827
11 2013-05-01    xirrA -0.173041
12 2013-05-01    xirrD -0.176014
13 2013-05-01    xirrE -0.240936
14 2013-06-01    xirrF -0.250384
15 2013-06-01    xirrC -0.144525
16 2013-06-01    xirrB -0.161093
17 2013-06-01    xirrG -0.158623
18 2013-06-01    xirrE -0.214767
19 2013-06-01    xirrD -0.154659
20 2013-06-01    xirrA -0.148461
21 2013-07-01    xirrF -0.224782
22 2013-07-01    xirrG -0.138918
23 2013-07-01    xirrB -0.138811
24 2013-07-01    xirrE -0.192705
25 2013-07-01    xirrA -0.126490
26 2013-07-01    xirrC -0.127239
27 2013-07-01    xirrD -0.137008

code:

plot = ggplot(lng,aes(x='date',y='value',color='variable'))+geom_line(size=2)+\
    scale_color_brewer(type = 'qual', palette = 1)+\
    ggtitle('XIRR by Date for multiple models')+xlab('Date')+ylab('XIRR')
print plot

I get this plot back:

![multiplot](https://cloud.githubusercontent.com/assets/3620202/5782324/bf1de206-9d7f-11e4-9477-4dadb216d10c.jpg)
What am I doing wrong?  I expected a render of all 7 variables ('xirrA'...'xirrG').  Also ,the value assignment is all wrong.  When plotted individually these are 7 smooth line graphs.  

Thanks for the help.

**Comment by glamp** [comment]
fixed in 0.9.3
