### ISSUE TITLE
Proper Factor Function

### ISSUE THREAD

**Issue by stefaneng** [yhat/ggplot#40]
R has the 'factor' function: http://stat.ethz.ch/R-manual/R-devel/library/base/html/factor.html

Is there interest in implementing this so we can write:

    p = ggplot(mtcars, aes(factor(cyl), mpg))
    p + geom_boxplot()

instead of:

    p = ggplot(mtcars, aes('factor(cyl)', mpg))
    p + geom_boxplot()

**Comment by glamp** [comment]
fixed in 0.9.3
