### ISSUE TITLE
Contribute examples to pandas

### ISSUE THREAD

**Issue by janschulz** [yhat/ggplot#401]
Pandas is currently deprecating their rplots (trelis plots, what we call faceting) module and it would be nice if ggplot examples are contributed to their examples to replace them.

I don't think we are currently ready for primetime yet, as we don't handle categorical data in faceting very well. So contribute there after fixing that problem at our side...

See here:
http://pandas.pydata.org/pandas-docs/version/0.14.1/rplot.html
https://github.com/pydata/pandas/issues/3445
https://github.com/pydata/pandas/pull/9357

**Comment by jorisvandenbossche** [comment]
Some difficulties/missing things that I encountered when I tried to convert the examples:

* I first tried to use `facet_wrap` giving it a list (which gave a not so informative error message), but then used (correctly I suppose) `facet_grid`. Thing is: both have no docstring, and the example pages on the website are broken (no images visible): http://ggplot.yhathq.com/docs/facet_grid.html and http://ggplot.yhathq.com/docs/facet_wrap.html
* When doing this:

  ```
ggplot(tips_data, aes(x='total_bill', y='tip')) +\
    geom_histogram() +\
    facet_grid("smoker", "sex")
  ```
  The y-label showed 'tip', which is not correct I think as I plotted a histogram, not a 2D plot (OK, I provided the `y` variable myself, but is is not fully correct)
* Missing functionality (as far as I can see): something to do the `rplot.GeomPolyFit(degree=2)` and `rplot.GeomDensity2D()`

So actually, the basic examples already can already be done, it is more some details/more advanced functionality that are missing.

**Comment by glamp** [comment]
seems off topic
