### ISSUE TITLE
Installing ggplot in a py3 environment

### ISSUE THREAD

**Issue by psychemedia** [yhat/ggplot#406]
I've been installing ggplot into a python3 environment (with all the required libraries already installed using pip3) and wondering why my ggplot install has been taking such a long time... I think the reason is that the ggplot installer loads all the libraries in at the 2.7 level *which I don't require*. Is there a simple way round this?

**Comment by JanSchulz** [comment]
I'm not sure that this is a ggplot error: looks more like pip is run via the wrong python version...

Can you post the output of both the following commands:
```
pip --version
python --version
```

**Comment by psychemedia** [comment]
My setup is a vagrant/puppet script that installs a load of python libraries under pip3:

    !pip --version
    >pip 6.0.6 from /usr/local/lib/python3.4/dist-packages (python 3.4)
    #I actually call the install from pip3 which has the same version number

There is a version of py 2.7 on the machine:

    !python --version
    >Python 2.7.6

but that's not what the point of the installation is. The point is to install libraries using pip3 for use with py 3 called via:

    ipython3 notebook --pylab inline --ip 0.0.0.0

When I watch the machine build, I have already explicitly installed the libraries (using pip3) that ggplot has as requirements. When puppet installs, the ggplot step takes a very long time - all I can think is that the dependencies are being loaded in again?

In my original issue I thought it might be because of dependency libraries being loaded in to the py2.7 context. However, if I ssh in to the VM, whilst I can import eg scipy or numpy into `python3`, those modules aren't found in the `python` (ie (`python27`) context. So what I'm wondering now is: *could ggplot be forcing the installation of the dependency files even though they have already been installed?*

From the repeated issues patching ggplot for use with py3 (please don't take that as a criticism - it's not meant to sound that way!) it seems that install tests aren't necessarily being run in a py3 context?

For my purposes, I want to be in control of what's getting installed in the machine for QA (and 5 year maintenance) purposes, with dependencies being explicitly listed and ordered via the puppet file. So I don't really want the ggplot installer reinstalling stuff if I've already taken it into account. (It shouldn't really do that anyway, should it, if the dependency is already met?)

**Comment by JanSchulz** [comment]
In my experience it does not. Not sure what is happening here :-(

**Comment by JanSchulz** [comment]
Do you still have open patches for py3? Our travis unittests run under py3 but it could be that something which is not yet covered via unittests is broken... patches would definitely be welcome!

**Comment by psychemedia** [comment]
I don't know - getting superstitious now; just tried reinstalling from command line (I'm pulling on this git version) and the download from github is really slow (even compared to other large installation downloads).

Will try to check this further bit will close for now as "my bad"... :-(

**Comment by JanSchulz** [comment]
Not sure if this is happening: https://github.com/pydata/patsy/issues/5 -> pip sometimes updates packages. If no clue what the mentioned "some circumstances" are :-(
