### ISSUE TITLE
Hatch support in geom_bar

### ISSUE THREAD

**Issue by wanglongqi** [yhat/ggplot#419]
I know due to restriction of grid system in R, ggplot2 does not provide support for hatch in geom_bar. However, matplotlib supports [hatches](http://matplotlib.org/examples/pylab_examples/hatch_demo.html). I do not understand the underlay mechanism of ggplot, but I think it is possible to add hatch support in geom_bar. Any further consideration that this feature should not be included in the package?

**Comment by has2k1** [comment]
I have such stuff (including partial filling of points, left, right, top bottom) on my radar once everything [else](#360) is out of the way.

**Comment by wanglongqi** [comment]
@has2k1 Woo, it is a large improve to current implements. Any plans to add the hatch support in future version?

**Comment by has2k1** [comment]
Yes it will be added as an aesthetic and there will be a `scale_hatch` for it.

**Comment by wanglongqi** [comment]
That's great! Since #360 rewrites almost everything, is it possible the new version can be extended to support 3D plots? If it is flexible enough to be extended to support 3D plots, it will be really great.

**Comment by has2k1** [comment]
I have not thought about 3D plots. Hadley Wickham has though and he does not think they represent information that well (I don't remember where I read that). Also, it is not immediately clear to me how they would fit into the existing framework without too much work.

**Comment by wanglongqi** [comment]
Maybe Hadley is right. 3D plots are quite different from 2D plots. If you cannot rotate and zoom it, the figure is not useful.
