### ISSUE TITLE
Save ggplot object

### ISSUE THREAD

**Issue by wanglongqi** [yhat/ggplot#420]
It is known matplotlib currently has limited support on saving matplotlib figure to disk (not saving to image files, but the raw figure object). In R, ggplot figure can be saved as a ordinary R object. However, in current implementation, ggplot object in python are not able to save to disk.

I tried to use `pickle` class to save ggplot object to disk, but get following error

	TypeError: can't pickle module objects

Because saving the object to disk which can be loaded for further similar figure is a important feature for ggplot, I think this feature should be added to ggplot in python.

**Comment by JanSchulz** [comment]
Can you give an usecase (e.g. when is it easier to load a ggplot object than recreating it?).

**Comment by wanglongqi** [comment]
@JanSchulz As is said in the ggplot book:

	Save a cached copy of it to disk, with save(). This saves a complete copy
	of the plot object, so you can easily re-create that exact plot with load().

I understand you can always clean up all your test codes to a final version of the figure, and write the data and script out. Then re-create the plot. But there will be at least one data file and one script. If you want to send a figure to someone else, you have to find the correct data file and script file. Or maybe you also need load some data file, then write a part of it to a new file. It is not convenient. Keep the data and figure structure in one file, you can manage your figures much more easier.

**Comment by JanSchulz** [comment]
I'm still not convinced:

* You still need a file (pickle of the ggplot object) and a script (how to load it and how to display it) and at least I would prefer a script where I can see what it is doing (and change it) and the plain data file than a magic file which I can't change and a "how to get it to display" script.
* There is no time saving, as the main part is afterwards in the `draw()` (which happens when you return the file in ipython or use `print(ggobject)` to display it), where in most cases a lot of dataframe actions happen, which can take seconds for bigger datasets. Constructing the object from scratch should take more or less the same time as unpickling it.

Pickling the ggplot object itself should be relatively easy: it's mostly getting to figure out, which properties have to be saved (e.g. all the geoms, data, config values,...) and how to reconstruct such an object form the pickle data.

**Comment by has2k1** [comment]
Well I think ggplot2 has the `save()` for history reasons. First, the ggplot system is a slow way to plot, (the plot building process is quite heavy) but it was much much slower until (I believe) a sponsored refactoring of the code base. With that and computers getting faster since ggplot2's inception the necessity for `save()` is not as strong.

**Comment by wanglongqi** [comment]
@JanSchulz You may want to check why there are similar question on how to save matplotlib object [here](http://stackoverflow.com/questions/4348733/saving-interactive-matplotlib-figures). I think it is possible to save a figure file, you just need load and print to get the figure. (The same as .fig file in Matlab.) It will not time saving, since the matplotlib object is not pickle-able, the matplotlib object must be reconstructed in order to get the figure. I think this function is just a easy way to transfer figure from one to another. It is even possible to make it a standard file type to contain figure, as .fig in Matlab.

@has2k1 I think maybe it is not a historical reason. One advantage of grid system is it is device independent, which enable its object can be saved and converted to other formats easily. For some users who is familiar with script and coding, having the codes is a better way to control the progress. But there are many other users out there, who is afraid of seeing codes and terminals. They want drag one file and open one figure, and drag another file open another one. However, I must admit if pickle matplotlib object is not possible, add this function may need an alternative representation of ggplot object, which may require a lot of modification.

**Comment by JanSchulz** [comment]
@wanglongqi: The above SO question also does not answer the "why this is more convenient than sending data+script"-question :-(

Just to make sure what's involved to "just send the ggplot figure over": the user would still need to install the same things as you have on your computer (python, matplotlib, ggplot, pandas, numpy -> most of which have native code which tends to complicate things on windows), you would need to send two files (the pickle of the ggplot object (which has in it a data (pandas/numpy) object and the ways this should be transformed to the final figure (the internal state of the ggplot object)) and a (slightly smaller) script which loads the pickle and then displays the figure.

Note that even when loaded from pickle, it will still need to do the (potentially costly) ggplot magic to transfer this to a matplotlib figure and matplotlib will do it's own magic (also potential costly) to transfer this figure to plot. So there is no timesaving at all!

From the handling point, this is also in no way different to sending the data itself and the script to transform this data into a plot via gpplot calls, as long as there is no app which lets you do a "Open ggplot plot".

Doing a pickle save will mean that we will have to keep the way we do our internal state, which is probably not desirable until ggplot-python is feature complete (@has2k1 has a rewrite of the current codebase, which more or less changes everything in the internal state...). The alternative is to add compatibility code to make it possible to load old states in newer code, which is a nightmare all in itself. Note that the above SO question also mentioned that " it works so poorly an MATLAB", so matlab seems that they have the same problem.

So, as long as there is no "open ggplot plot" in some "install everything via *.exe"-thingy, I still don't think this is worth it. I don't know if there is such an environment for matplotlib, but if yes, then a alternative would be to get the figure which `fig = ggobject.draw()` produces and save that (the SO question mentions that saving the matplotlib figure is possible now) and send it over.

**Comment by wanglongqi** [comment]
@JanSchulz Maybe you are right. Supporting saving in this stage is not wise.
On Windows there are several choice you can "install everything via *.exe"-thingy, currently Python(x,y) maybe the most widely used free distribution. Matplotlib and its dependencies are installed as default. 

Since ggplot does not support save figures out, it is sure "there is no app which lets you do a "Open ggplot plot"". But if the function works well, it is hopefully there will be an app support this function.

For the .fig file support in Matlab, the problem only occurs in early Matlab version. Since Matlab v7, the whole plot system was upgraded, the support is quite smooth now.

The pickle support for matplotlib is still not stable, and it seems pickle support in matplotlib is backend dependent. Since they are still working on it, the support will be stable in near future.  Maybe the best way to save ggplot figure is to use pickle support from matplotlib, but there will be a matplotlib figure instead of a ggplot one.
