### ISSUE TITLE
Plotting an empty DataFrame gives IndexError: index out of bounds

### ISSUE THREAD

**Issue by tdsmith** [yhat/ggplot#425]
Attempting to plot an empty data frame, like:
```python
empty_df = pd.DataFrame({'x_col': [], 'y_col': []})
g = gg.ggplot(empty_df, gg.aes(x='x_col', y='y_col')) + gg.geom_path()
```
gives an IndexError from [this line](https://github.com/yhat/ggplot/blob/e2c08b2fd85f714d53c6a815ca898be71f867162/ggplot/ggplot.py#L358) in draw():
```python
elif "data" in locals() and ("x" in data) and isinstance(data["x"][0], datetime.date):
```

I noticed this because I had a plot with two geoms with different data; one of the data sources was sometimes empty, leading to this failure.

Here's a notebook that provokes the failure and then illustrates the thing that failed for me: http://nbviewer.ipython.org/gist/tdsmith/ef35c52b8a5e2ca916fd

**Comment by glamp** [comment]
fixed in 0.9.3
