### ISSUE TITLE
bad index ggplot

### ISSUE THREAD

**Issue by benrifkind** [yhat/ggplot#435]
I have a macbook pro with Yosemite (10.10.2)

ipython - 3.1.0
pandas - 0.16.2
ggplot - 0.6.5

If the dataframe is not indexed from zero, there is a 'Key Error: 0' error.
Here's an example of code that does not work:
    
    df = pd.DataFrame({'x':np.arange(1,5), 'y':np.arange(1,5)})
    df.index = np.arange(1,5)
    ggplot(df_index, aes(x='x', y='y')) + geom_point()

The error I get is below.

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/Users/Ben/anaconda/lib/python2.7/site-packages/IPython/core/formatters.pyc in __call__(self, obj)
    688                 type_pprinters=self.type_printers,
    689                 deferred_pprinters=self.deferred_printers)
--> 690             printer.pretty(obj)
    691             printer.flush()
    692             return stream.getvalue()

/Users/Ben/anaconda/lib/python2.7/site-packages/IPython/lib/pretty.pyc in pretty(self, obj)
    405                             if callable(meth):
    406                                 return meth(obj, self, cycle)
--> 407             return _default_pprint(obj, self, cycle)
    408         finally:
    409             self.end_group()

/Users/Ben/anaconda/lib/python2.7/site-packages/IPython/lib/pretty.pyc in _default_pprint(obj, p, cycle)
    525     if _safe_getattr(klass, '__repr__', None) not in _baseclass_reprs:
    526         # A user-provided repr. Find newlines and replace them with p.break_()
--> 527         _repr_pprint(obj, p, cycle)
    528         return
    529     p.begin_group(1, '<')

/Users/Ben/anaconda/lib/python2.7/site-packages/IPython/lib/pretty.pyc in _repr_pprint(obj, p, cycle)
    707     """A pprint that just redirects to the normal repr function."""
    708     # Find newlines and replace them with p.break_()
--> 709     output = repr(obj)
    710     for idx,output_line in enumerate(output.splitlines()):
    711         if idx:

/Users/Ben/anaconda/lib/python2.7/site-packages/ggplot/ggplot.pyc in __repr__(self)
    109     def __repr__(self):
    110         """Print/show the plot"""
--> 111         figure = self.draw()
    112         # We're going to default to making the plot appear when __repr__ is
    113         # called.

/Users/Ben/anaconda/lib/python2.7/site-packages/ggplot/ggplot.pyc in draw(self)
    352                         ax.xaxis.set_ticklabels(self.xtick_labels)
    353                 # need to handle cases when there's no geom_bar/hist
--> 354                 elif "data" in locals() and ("x" in data) and isinstance(data["x"][0], datetime.date):
    355                     # "did matplotlib do a decent job of making the label" check
    356                     if np.log10(ax.get_xticks()[0]) > 6:

/Users/Ben/anaconda/lib/python2.7/site-packages/pandas/core/series.pyc in __getitem__(self, key)
    519     def __getitem__(self, key):
    520         try:
--> 521             result = self.index.get_value(self, key)
    522 
    523             if not np.isscalar(result):

/Users/Ben/anaconda/lib/python2.7/site-packages/pandas/core/index.pyc in get_value(self, series, key)
   1593 
   1594         try:
-> 1595             return self._engine.get_value(s, k)
   1596         except KeyError as e1:
   1597             if len(self) > 0 and self.inferred_type in ['integer','boolean']:

pandas/index.pyx in pandas.index.IndexEngine.get_value (pandas/index.c:3113)()

pandas/index.pyx in pandas.index.IndexEngine.get_value (pandas/index.c:2844)()

pandas/index.pyx in pandas.index.IndexEngine.get_loc (pandas/index.c:3704)()

pandas/hashtable.pyx in pandas.hashtable.Int64HashTable.get_item (pandas/hashtable.c:7204)()

pandas/hashtable.pyx in pandas.hashtable.Int64HashTable.get_item (pandas/hashtable.c:7142)()

KeyError: 0

**Comment by jdmcbr** [comment]
I just ran into the same issue. I have the same versions of all the relevant packages as the OP.

OS: Ubuntu 14.04
ggplot: 0.6.5
pandas: 0.16.2
ipython: 3.1.0

**Comment by benine** [comment]
I've run into this issue several times lately and have resorted to including a dummy value for x=0, but this will make for incorrect plots when it comes time to publish

I'm currently running a macpro with yosemite(10.10.4):
ggplot: 0.6.5
pandas: 0.16.2
ipython: 3.1.0

**Comment by glamp** [comment]
fixed in 0.9.3
