### ISSUE TITLE
BUG: the breaks function of scale_y_continuous can't work

### ISSUE THREAD

**Issue by catyaoheng** [yhat/ggplot#438]
This is my code

0. df = pd.DataFrame(dict(fpr=X, tpr=Y))
1. auc = metrics.auc(x,y)
2. image = ggplot(df, aes(x='fpr', y='tpr', ymin=0, ymax='tpr')) +\
3.     geom_area(alpha=0.1) +\
4.     geom_line(aes(y='tpr')) +\
5.     geom_abline(linetype='dashed') +\
6.     geom_point(x=x, y=y, color='steelblue', size=50) +\
7.     scale_x_continuous(breaks=[i*0.25 for i in range(5)], limits=[0,1.007]) +\
8.    scale_y_continuous(breaks=[i*0.1 for i in range(11)], limits=[0,1.01]) +\
9.     ggtitle("ROC Curve w/ AUC=%s" % str(auc))

line 8
scale_y_continuous(breaks=[i*0.1 for i in range(11)], limits=[0,1.01]) +\

the breaks does not work
the output image still shows the default y-axis breaks

hope someone can fix it

**Comment by catyaoheng** [comment]
1

**Comment by glamp** [comment]
fixed in 0.9.3
