### ISSUE TITLE
Legent problem: Charaters are converted to lower case by itself.

### ISSUE THREAD

**Issue by notilas** [yhat/ggplot#441]
All AP names are capital letters, but the first one "0CAF" appears as "0Caf" in the legend.
Also the column name is "AP' not "Ap", which is automatically changed in ggplot.

![problem](https://cloud.githubusercontent.com/assets/8880506/8812344/65c36cf8-2fb0-11e5-9434-7367959b42d5.PNG)

**Comment by glamp** [comment]
fixed in 0.9.3
