### ISSUE TITLE
scale_color_manual: can I define my own mapping rather than a list?

### ISSUE THREAD

**Issue by xguse** [yhat/ggplot#442]
The docs [here](http://ggplot.yhathq.com/docs/scale_colour_manual.html) show a dict in the usage section, but only lists are shown after that.  Its baffling me that this seems so rare a use case that it has not come up or been coded in as a matter of course.  Am I missing something?

Ideally I would like all of my figures in my paper to use the same colors for particular sampling sites regardless of whether ALL sites are present in every figure and ALWAYS in the same order.

Is this possible?

Gus

**Comment by has2k1** [comment]
That usage snippet does not make much sense, the colour applies to the points not the axes. I don't fully understand what you are trying to do, but it seems like you need a *site* categorical value so that `aes(color='site')`.

In any case, the scales as implemented in master turned out to be so different in form as compared to ggplot2, I reimplemented them in PR #360. You can try out that branch (with that caveat that I occasionally rebase). If you find it usable to some satisfaction, I have some "unpushed" commits that I can make public.

**Comment by xguse** [comment]
I already have a categorical `site` column and I __am__ using `aes(color='site')`.

I have thrown together an ipython [notebook](http://nbviewer.ipython.org/github/xguse/ipy_notebooks/blob/master/YALE/ddrad58/2015-07-25__PCAdapt_figures_set_colors_example.ipynb) that hopefully better explains what I am dealing with and what I would like.

Some main points:

- I set up a manual color scale in cell 2.
    - commented out is what I would __like__ to be able to pass into `gp.scale_color_manual()`
- [cells 7 and 8](http://nbviewer.ipython.org/github/xguse/ipy_notebooks/blob/master/YALE/ddrad58/2015-07-25__PCAdapt_figures_set_colors_example.ipynb#One-data-set-has-a-subset-of-the-other's-members-for-site) show that one dataset has an extra value for `site` which will end up causing the problem later.
- [cell 9](http://nbviewer.ipython.org/github/xguse/ipy_notebooks/blob/master/YALE/ddrad58/2015-07-25__PCAdapt_figures_set_colors_example.ipynb#Begin-plotting-examples) shows what my dataframes look like.
- [The remaining cells](http://nbviewer.ipython.org/github/xguse/ipy_notebooks/blob/master/YALE/ddrad58/2015-07-25__PCAdapt_figures_set_colors_example.ipynb#We-plot-one-data-set-and-get-colors-assigned) show how things go wrong when you can't lock color assignments to values of `aes(color='site')`.


I hope this helps.  Thanks again for the time you take to look at these issues.  Hopefully, I am just overlooking functionality somewhere.

Gus

**Comment by has2k1** [comment]
I've fixed this but you would have to install the *rewrite* branch at https://github.com/has2k1/ggplot

Maybe this could be helpful
```
pip install git+https://github.com/has2k1/ggplot.git@rewrite
```
