### ISSUE TITLE
Wrong number of labels in legend; wrong color assignments using geom_point()

### ISSUE THREAD

**Issue by DmitriR** [yhat/ggplot#444]
I suspect these are related issues, so I'm reporting them together. 
Possibly related to #376  
```
( ggplot(aes(x='carat', y='price', color='clarity'), data=diamonds) 
    + geom_point() 
    + scale_color_brewer(type='seq', palette='Reds') )
```
produces 3 labels and visibly incorrect (vs. img generated in R) point colors.
The dataset is correct:
```
diamonds.clarity.nunique()
```
reports 8. 

ggplot version: 0.6.5
installed with pip install -I git+git://github.com/yhat/ggplot.git
Python 3.4.3 |Anaconda 2.3.0 (x86_64)| (default, Mar  6 2015, 12:07:41) 
OSX 10.9.5

**Comment by glamp** [comment]
fixed in 0.9.3
![image](https://cloud.githubusercontent.com/assets/1409333/15691732/7bedfe62-2758-11e6-90b7-9442633e4ad0.png)
