### ISSUE TITLE
is ggplot dead?

### ISSUE THREAD

**Issue by naught101** [yhat/ggplot#449]
What's going on? There has been one commit this year. There are pull requests waiting with no response. Is this project going to pick up again? Does it need new maintainers? Does it need to be forked?

This is a really valuable tool - there is nothing else that compares to the grammar of graphics, and no other GoG implementation in python. But at the moment, it still needs a fair bit of work to be useful. Seems a shame to get it 80% there and then stop...

**Comment by eco32i** [comment]
Apparently there is a big [rewrite](https://github.com/yhat/ggplot/pull/360) in the works but not clear when it's gonna be ready. I tried the branch mentioned there but it's not working for me.

**Comment by has2k1** [comment]
@naught101, the problem is the project got trapped into implementing the API instead of a GoG.

@eco32i, what problem are you having with the branch? FYI, I am the author.

**Comment by eco32i** [comment]
@has2k1 when I install it in virtualenv and try `from ggplot import *` this is what I get:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-02aeb6e281ab> in <module>()
----> 1 from ggplot import *

/home/ilya/.virtualenvs/proscatter/local/lib/python2.7/site-packages/ggplot/__init__.py in <module>()
     19 __version__ = '0.6.6'
     20 
---> 21 from .qplot import qplot
     22 from .ggplot import ggplot
     23 from .components import *

/home/ilya/.virtualenvs/proscatter/local/lib/python2.7/site-packages/ggplot/qplot.py in <module>()
      5 from .components import aes
      6 from .geoms import geom_point, geom_bar, geom_boxplot, geom_histogram, geom_line
----> 7 from .geoms.chart_components import xlab as xlabel
      8 from .geoms.chart_components import ylab as ylabel
      9 from .geoms.chart_components import ggtitle

ImportError: No module named chart_components
```

**Comment by has2k1** [comment]
@eco32i, You can now try it (the rewrite branch) out.

**Comment by eco32i** [comment]
@has2k1 Yep, working now. Thanks a bunch! Will definitely try using it now. Should I report issues, if any, here?

**Comment by has2k1** [comment]
I know there are probably many issues and I have been wry of getting bombarded, but if they are found they need to be addressed. You can post them at #360 in a single post, just keep editing it.

**Comment by naught101** [comment]
Kind of unfortunate that you can't change the title of a github issue... #360 has a kind of irrelevant name now...

Thanks for that update @has2k1, I was wondering why I couldn't get the tests to even run. Now I'm getting hundreds of errors. Yay! :P

**Comment by has2k1** [comment]
@naught101, the tests are based on the old implementation and for the majority, until the rewrite is mature enough it does not make much sense to fix them.

**Comment by naught101** [comment]
@has2k1 Yeah, I know, that was just a joke :)

I will try to have a play around with the re-write. Do you have any idea how different the final API will be to the ggplot2 API?

**Comment by has2k1** [comment]
The goal is to have no difference other than those necessary due to the differences between `R` and `Python`.

**Comment by LilySnow** [comment]
It is sad that this project is not updated now. It would be a very useful tool.

**Comment by eco32i** [comment]
It was forked a while ago and completely rewritten as far as I know: [plotnine](https://github.com/has2k1/plotnine)
