### ISSUE TITLE
save in a BytesIO

### ISSUE THREAD

**Issue by mhooreman** [yhat/ggplot#450]
Hello,

I'm usually exporting my charts as base 64 PNG data, in order to embed them into HTML reports.

Using matplotlib, I'm able to do the following, inside my "Report" class (pyhon3):

     def addPlot(self, fig):
         """Adds a matplotlib figure to the report, as PNG encoded in base 64
         - fig: a matplotlib figure
         """
         imgdata = io.BytesIO()
         fig.savefig(imgdata, format='png')
         imgdata.seek(0)  # rewind the data
         uri = 'data:image/png;base64,' + urllib.parse.quote(base64.b64encode(imgdata.getbuffer()))
         self._body += '\n<img src="%s" style="border:None" alt="Report image" />\n' % uri

Unfortunately, even if ggplot is using matplotlib in the background, I can't find any way to get the matplotlib figure object from the ggplot object, so that I have no access to the savefig method.

Can you add this kind of feature?

Thankks a lot and best regards.

**Comment by has2k1** [comment]
Have you tried `plt.gcf()` after plotting with ggplot.

**Comment by mhooreman** [comment]
Thanks Hassan
Unfotunately, gcf returns an empy figure

**Comment by has2k1** [comment]
I think this should work

```
gg = ggplot(...) + geom_blah()
fig = gg.draw()
```

**Comment by mhooreman** [comment]
Thanks. Indeed, I didn't know about the draw.

I guess that with gcf, it returned nothing because draw was not called.

Now, works perfectly with fig = fig.draw.

Thanks a lot!
