### ISSUE TITLE
Calls to deprecated matplotlib functions

### ISSUE THREAD

**Issue by psychemedia** [yhat/ggplot#458]
As matplotlib evolves, `ggplot` functions could start to rot. For example

    from ggplot import *
    ggplot(aes(x='carat',y='depth'),data=diamonds)+geom_line()+ggtitle('Demo')

Raises the warning:

    /usr/local/lib/python3.4/dist-packages/matplotlib/__init__.py:872: 
      UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle;
      please use the latter.
    warnings.warn(self.msg_depr % (key, alt_key))

**Comment by charlie-turner** [comment]
Am I correct in thinking this issue arrived with matplotlib 1.5.0? 

This similar seaborn issue suggests as much: https://github.com/mwaskom/seaborn/issues/778.

**Comment by glamp** [comment]
fixed in 0.9.3
