### ISSUE TITLE
Missing support for grouped bar charts (position='dodge')

### ISSUE THREAD

**Issue by jrk** [yhat/ggplot#464]
Does ggplot not (yet) include any support for alternate positioning modes for `geom_bar` (in particular, `dodge`, which is the only widely discussed way to do grouped instead of stacked bar charts)? All but one of the plots in [this standard example](http://www.cookbook-r.com/Graphs/Bar_and_line_graphs_(ggplot2)/#bar-graphs) seem not to be achievable.

I saw discussion of this in #324 & #325, but #324 seems to have been dropped, and #325 never added `dodge` support.

**Comment by jrk** [comment]
I'm open to obvious workarounds, and will update this to either be a descriptive feature request ("`geom_bar` should support `position='dodge'`") or close it as an answered question depending on whether I missed something in the 18 months since #325, or if this is indeed not yet possible.

**Comment by glamp** [comment]
0.9.3 has support for stack, fill, and dodge which is default
