### ISSUE TITLE
UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.

### ISSUE THREAD

**Issue by Arn-O** [yhat/ggplot#468]
This issue is not blocking.

A warning message is thrown away with ``geom_bar``, check my notebook, cell 12:

https://github.com/Arn-O/udacity-intro-data-science/blob/master/subway_viz1.ipynb

![screen shot 2016-02-02 at 23 29 00](https://cloud.githubusercontent.com/assets/3259119/12831054/a371c12a-cb92-11e5-9c8a-272fd1fdbe5b.png)

It was working fine until a recent update of the prerequisites.

**Comment by glamp** [comment]
fixed in 0.9.3

**Comment by Arn-O** [comment]
Looks nicer now:

![screenshot from 2016-06-01 19-33-58](https://cloud.githubusercontent.com/assets/3259119/15719383/f50c389a-282f-11e6-8d47-dfc2f2b4afc4.png)

Thank you for your help!
