### ISSUE TITLE
TypeError: __init__() got multiple values for keyword argument 'width'

### ISSUE THREAD

**Issue by Arn-O** [yhat/ggplot#469]
The ``TypeError`` message is thrown out with ``facet_grid``, the graphics is not displayed. See the cell 16 of this notebook:

https://github.com/Arn-O/udacity-intro-data-science/blob/master/subway_viz2.ipynb

![screen shot 2016-02-02 at 23 29 34](https://cloud.githubusercontent.com/assets/3259119/12831291/cc5b3fca-cb93-11e5-9743-1cce1ed76f93.png)

**Comment by ragrawal** [comment]
+1

**Comment by darastraussalbee-ch** [comment]
+1 also

**Comment by glamp** [comment]
fixed in 0.9.3
![image](https://cloud.githubusercontent.com/assets/1409333/15690311/f6856f8c-2750-11e6-8aeb-e534f71b45ae.png)

**Comment by Arn-O** [comment]
That was much expected. It works, thanks a lot!

Ar.
