### ISSUE TITLE
Time series dates do not display correctly in x-label when using stat_smooth() 

### ISSUE THREAD

**Issue by kstohr** [yhat/ggplot#477]
Thanks to all for great work on porting ggplot to python. Noticed dates in a timeseries plot display correctly for geom_line()  but not when plotting with stat_smooth () function.  See issue and sample code here: 

https://github.com/kstohr/LSM_Immigration/blob/master/immigration_explore-ggplot%20issue.ipynb

Would love to find a way to display dates correclty using stat_smooth () on time series.

**Comment by glamp** [comment]
fixed in 0.9.3 though the default labels aren't great.

```print ggplot(meat, aes(x='date', y='beef')) + stat_smooth() + scale_x_date(labels=date_format('%Y'))```

You can use `scale_x_date` to make them pretty 😄 

![image](https://cloud.githubusercontent.com/assets/1409333/15690349/21663b96-2751-11e6-94dd-00a20729c908.png)

**Comment by kstohr** [comment]
Gracias!!! Huge tks.

On Tuesday, May 31, 2016, Greg Lamp <notifications@github.com> wrote:

> fixed in 0.9.3 though the default labels aren't great.
>
> print ggplot(meat, aes(x='date', y='beef')) + stat_smooth() +
> scale_x_date(labels=date_format('%Y'))
>
> You can use scale_x_date to make them pretty 😄
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1409333/15690349/21663b96-2751-11e6-94dd-00a20729c908.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/yhat/ggplot/issues/477#issuecomment-222818925>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AH1md2ObcZUIo3cCk10ueiZJCgONt9Qvks5qHKFigaJpZM4IYSHY>
> .
>


-- 
Sent from a cloud, with a chance of typos.
