### ISSUE TITLE
How can I print unicode(e.g. Korean) on a plot?

### ISSUE THREAD

**Issue by hurcy** [yhat/ggplot#482]
Hello,

I tried to print unicode on a plot, but I couldn't.
Only rectangles are printed.
I'm using this ggplot on Ubuntu 14.10, Python 2.7.11, anaconda 1.2.1.
Can you tell me how to fix this?

![figure_1](https://cloud.githubusercontent.com/assets/982262/15779282/63b74a3a-29d6-11e6-96c3-53b1539d9ae1.png)

Thanks!!

**Comment by glamp** [comment]
This works for me:

```
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from ggplot import *

print ggplot(mtcars, aes(x='mpg')) + geom_histogram() + xlab("Scrüm")
```
![image](https://cloud.githubusercontent.com/assets/1409333/15783228/f92d6fb8-2972-11e6-961f-5a6aa9f73f06.png)

**Comment by hurcy** [comment]
```
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from ggplot import *

print ggplot(mtcars, aes(x='mpg')) + geom_histogram() + xlab("한글")
```
Could you try this? It didn't work.
Maybe Korean font is not supported..?

**Comment by leezu** [comment]
Same happens with greek symbols (η, ε, etc.).

**Comment by gepcel** [comment]
@hurcy 
Did you solve your problem? I think this issue is not about unicode actually, it's about fonts.
@glamp can print the `"Scrüm"` because the default font includes the character.

You can try something like this (not ideal, but works):
```python
t = theme_gray()  # since this is the default theme
t._rcParams['font.family'] = "SimHei"  # You should replace this with some Korean font, this is for Chinese
print(ggplot(mtcars, aes(x='mpg')) + geom_histogram() + xlab("한글") + t
```

**Comment by hurcy** [comment]
@gepcel 
I tried your suggestion, but it didn't print properly.

I also tried this, but didn't work:
```
from matplotlib import font_manager, rc
import matplotlib
# local font support Hangul
# u'/usr/share/fonts/truetype/nanum/NanumGothic.ttf': 1,
krfont = {'family' : 'nanumgothic', 'weight' : 'bold', 'size'   : 10}
matplotlib.rc('font', **krfont)
```

**Comment by gepcel** [comment]
@hurcy 
Well, sorry. Try this:
```python
g = ggplot(mtcars, aes(x='mpg')) + geom_histogram() + xlab("한글")
t = theme_gray()
t._rcParams['font.family'] = 'nanumgothic'
g+t
```
I was testing line by line among many other things, and put some together as an answer. It turns out the order matters.
`matplotlib.rc('font', **krfont)` shouldn't work.
