### ISSUE TITLE
unhashable type: 'DatetimeIndex'

### ISSUE THREAD

**Issue by t0mst0ne** [yhat/ggplot#484]
After upgrade from ggplot 0.6.5 to current version, the following code got error 

print ( ggplot(df, aes(x=df.index, y='Crude')) + geom_line() )
unhashable type: 'DatetimeIndex'

where the df.index is pandas.tseries.index.DatetimeIndex

**Comment by glamp** [comment]
Did that work on 0.6.5?

**Comment by t0mst0ne** [comment]
oh yes, it did

**Comment by glamp** [comment]
Ok that's odd. I wouldn't have expected it to work with an index 😄 

Can you use `reset_index()` and then reference the index column?

**Comment by glamp** [comment]
will be fixed in next release

40c7e28fc016f0bd73a02f77985cfeec811c6a36
