### ISSUE TITLE
geom_line, geom_point order and Date Axis AutoFormat

### ISSUE THREAD

**Issue by jpryda** [yhat/ggplot#487]
[Could have been fixed in this newer version but for the previous version:]

The order of plotting geom_line and geom_point affects the scale_x_date immensely, to the point that if geom_point is used first there is a crazy amount of excess whitespace left and right of the datapoints.  

This is particularly hard to rectify since date limits can't be easily placed (in non-numeric form at least) on the axis.

**Comment by glamp** [comment]
thanks @jpryda! can you provide a reproducible sample?

**Comment by jpryda** [comment]
I'll try to tomorrow.  My previous code is pretty broken right now since upgrading.  geom_line() isn't working for multiple lines (whilst geom_step does).
