### ISSUE TITLE
ggsave and theme don't work

### ISSUE THREAD

**Issue by demis001** [yhat/ggplot#492]
I have installed the package using both ways, but  _'ggsave'_ and _theme_ aren't exist in the package. I have seen the update about ggsave on the issue you have created. 

pip install git+https://github.com/yhat/ggplot.git  OR pip install -U ggplot

For example this don't work

from ggplot import ggsave

Help?
Dereje

**Comment by glamp** [comment]
Hey @demis001 

Use the `.save` method on the plot you've created. For instance:

```
from ggplot import *
p = ggplot(mtcars, aes(x='mpg')) + geom_histogram()
p.save("my-plog.png")
```

**Comment by demis001** [comment]
Thank you!
I have seen the docs about that after I have created the issue. 

One more thing, how do adjust the axis label. For example I want to make the x label vertical. This don't work....

theme(axis_text_x = element_text(angle=90))

Dereje

**Comment by glamp** [comment]
Unfortunately it's not implemented yet 😦

**Comment by demis001** [comment]
How about coord_flip() to create horizontal bar?

**Comment by j0ma** [comment]
I saw the theme() class definition in the repository, but I take it it's not implemented? I'm trying to remove the margin from around the plot, similar to [theme(plot.margin=0) in R](http://docs.ggplot2.org/0.9.2.1/theme.html)

**Comment by glamp** [comment]
Don't have that either. Unfortunately i's one of those things that seems like it's really easy (just flip the x and y axis) but the way it's implemented makes it fairly challenging--it'll require writing a lot of new code. I will open a new issue for it!

**Comment by glamp** [comment]
@demis001 `element_text` is on master and should be released very soon! If you want to try it out you can install it using `pip install git+https://github.com/yhat/ggplot.git`

**Comment by demis001** [comment]
@lamp Thanks! I had Installed as you have suggested. I will look the docs for element_text.
