### ISSUE TITLE
Recommend that conda users install from conda-forge

### ISSUE THREAD

**Issue by pmlandwehr** [yhat/ggplot#494]
Just a heads up: there's a [recipe for `ggplot`](https://github.com/conda-forge/ggplot-feedstock) in [conda forge.](https://conda-forge.github.io/) As such, you could change out the conda recommendation from "use pip" to `conda install -c conda-forge ggplot`

**Comment by glamp** [comment]
Thanks. Updated the readme.67bfcaf64a0633e920390d2eaf9c06b90917b2b1
