### ISSUE TITLE
Feasibility of implementing geom_polygon?

### ISSUE THREAD

**Issue by ktaylora** [yhat/ggplot#495]
I do a lot of work with spatial data in 'R' and ggplot2 has been useful for map making. Has there been an attempt to port over [geom_polygon()](http://docs.ggplot2.org/current/geom_polygon.html) to ggplot?

**Comment by glamp** [comment]
Very feasible. There has not been an attempt but I can try to get it into the next release.

**Comment by glamp** [comment]
@ktaylora this is on master! you can try it out by running...

```
pip install git+https://github.com/yhat/ggplot.git
```

**Comment by ktaylora** [comment]
Awesome!  Will grab the update and poke around.
