### ISSUE TITLE
removing margin around a plot

### ISSUE THREAD

**Issue by j0ma** [yhat/ggplot#496]
I saw the theme() class definition in the repository, but I take removing the margin is not implemented? At least I didn't see a how-to notebook for it. 

I'm currently saving my plot in as a .png file, and embedding it in an email. However, there is excess whitespace on the left side of the x-axis which I'm trying to remove, similar to theme(plot.margin=...) in R. Is this currently possible? 

Here is a picture to clear things up a bit:

<img width="1111" alt="screen shot 2016-06-23 at 12 05 27 pm" src="https://cloud.githubusercontent.com/assets/10352674/16299913/33e1b55e-393d-11e6-8c8c-97721c9459d7.png">

**Comment by glamp** [comment]
Thank you for the well defined issue!

You're correct, there's no way to do this. `theme` is coming out in the next release. I will include `plot.margin` as an option 👍

**Comment by glamp** [comment]
```
from ggplot import *
print ggplot(mtcars, aes(x='mpg')) + geom_histogram() + theme(plot_margin=dict(bottom=0.2, left=0.2)) # can also do top, right
```
