### ISSUE TITLE
Unicode exception in python 3

### ISSUE THREAD

**Issue by niknoproblems** [yhat/ggplot#500]
I use Python 3.5.1  on Ubuntu 14.04   and I have that exception for any plot in 0.10.0 version of ggplot:
```
    270         if xlab:
--> 271             if isinstance(xlab, (str, unicode)):
    272                 xlab = element_text(xlab)
    273 
NameError: name 'unicode' is not defined
```

**Comment by nicktimko** [comment]
Probably an easy fix:

    import six
    # ...
        if isinstance(xlab, six.string_types):
    # ...
