### ISSUE TITLE
Acknowledge old contributors

### ISSUE THREAD

**Issue by janschulz** [yhat/ggplot#503]
Currently, the code looks like it was completely written by @glamp / yhat as the repository was completely reset instead of keeping the old git history.

I find that very unfortunate as a lot of code is still based on the old code which had quite a lot of contributors (e.g. I contributed to the theme system, py3 fixes (which mistakes are still in the new codebases) and the patsy usage to compute new columns on the fly, a lot of fixes; also the old unittest framework; there were a lot other who contributed -> see the closed PRs).

Could you please at least add a prominent acknowledgement to these contributors?

The old contributors can still be seen here: https://github.com/has2k1/ggplot/graphs/contributors (although that codebase has seen quite a lot of changes due to the @has2k rewrite).

**Comment by glamp** [comment]
Whoops sorry @janschulz! I didn't mean to do that. I will add everyone back in.

**Comment by glamp** [comment]
6ab8085669f540c2770eda30137e69689ea3363c
