### ISSUE TITLE
No way to set number of bins in geom_histogram

### ISSUE THREAD

**Issue by ChickenProp** [yhat/ggplot#513]
As far as I can tell, a histogram will always use 10 bins, the default from matplotlib's ax.hist().

This can be fixed by adding `'bins': 10` to `geom_histogram.DEFAULT_AES`, so it's easy to monkeypatch around:

    geom_histogram.DEFAULT_AES['bins'] = 10
    ggplot(data, aes(x='column')) + geom_histogram(bins=30)

But I don't know whether a fix in the repository would want `bins` as an aesthetic. (This implies you could write `aes(x='column1', bins='column2')`, which seems meaningless.)

The etiology of the bug is:

- `geom_histogram.plot` passes kwargs to [`ax.hist`](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.hist) from the variable `params`
- `params` gets set from the return value of `geom._get_plot_args`
- `_get_plot_args` constructs the parameters as a dict from the global aes, the geom aes, and arguments passed directly to the `geom` initializer.
- BUT it removes any parameters not found in the set `self.VALID_AES`.
- `self.VALID_AES` takes its members from `self.REQUIRED_AES`, and the keys of `self.DEFAULT_AES` and `self._aes_renames`.
- So putting `bins` in `DEFAULT_AES` allows it to pass through `_get_plot_args`.

**Comment by ChickenProp** [comment]
A more general solution might be, in `geom._get_plot_args`:

        items = list(mpl_params.items())
        for key, value in items:
            if key not in self.VALID_AES:
                del mpl_params[key]
            elif key in self._aes_renames:
                new_key = self._aes_renames[key]
                mpl_params[new_key] = value
                del mpl_params[key]

change this third line to `if key not in self.VALID_AES and key not in self.params:`. `self.params` is the parameters passed directly to the geom, so it would allow `geom_histogram(bins=30)` but not `geom_histogram(aes(bins='column'))`

But I don't know what effects this would have elsewhere, and I don't have time to investigate right now.

**Comment by glamp** [comment]
@ChickenProp on master now bc5c9779646ba3a99dc355224a59b6d854507fb1

```
from ggplot import *

print ggplot(diamonds, aes(x='price')) + geom_histogram()
print ggplot(diamonds, aes(x='price')) + geom_histogram(bins=50)
```

![image](https://cloud.githubusercontent.com/assets/1409333/17253936/cd4afae8-5580-11e6-9acd-d8f624d92620.png)
![image](https://cloud.githubusercontent.com/assets/1409333/17253941/d02e35d6-5580-11e6-9bba-ba9e070605a9.png)
