### ISSUE TITLE
ggplot.show() method?

### ISSUE THREAD

**Issue by ChickenProp** [yhat/ggplot#520]
I feel like the `ggplot` objects would be served by a `.show()` method. Currently you're supposed to display them by printing them, but that also prints the `<ggplot: ...>` thing. You can avoid that by calling `repr()` instead of `print`, but that's unintuitive.

`.show()` could also accept optional width/height parameters, like `.save()` does, which would be useful in jupyter notebooks.

If there's no objection, I might be able to make a PR for this sometime soonish.

**Comment by glamp** [comment]
agreed. i will add it

**Comment by glamp** [comment]
f658c1a6be8e6218d73f604c400d4552efb80d4c
