### ISSUE TITLE
scale_color_manual not changing colors

### ISSUE THREAD

**Issue by hueykwik** [yhat/ggplot#521]
When I try to use scale_color_manual to change my color scheme, I still get the defaults:

`color_list = ["#FF0000","#0000FF"]
ggplot(train, aes(x='Age', y='PassengerId', color='Survived')) + geom_point() + scale_color_manual(values=color_list)`

![image](https://cloud.githubusercontent.com/assets/707311/17428145/27bc2bd6-5a9b-11e6-9b0f-00cb5acb32d3.png)

Running Python 3.5 and gplot-0.11.1.

**Comment by glamp** [comment]
`scale_color_manual` only works for discrete values. change your color parameter to a factor and you'll be good 👍 

```
ggplot(train, aes(x='Age', y='PassengerId', color='factor(Survived)')) + \
    geom_point() + \
    scale_color_manual(values=color_list)
```
