### ISSUE TITLE
geom_bar() only counts, does not stack or plot values

### ISSUE THREAD

**Issue by Arn-O** [yhat/ggplot#529]
Hi.

With ``geom_bar()``, I can plot a dataframe by the count of items, not by stacking the values. It fails also for a single value by class.

See my notebook:

https://github.com/Arn-O/udacity-intro-data-science/blob/master/subway_viz1.ipynb

The content of the dataframe is displayed in the cell 11. The ``geom_line()`` plot is working fine (cell 12),  but the ``geom_bar()`` only reports 1 (cell 13 and 14). I tried it on the ``diamonds`` dataframe, but got the same result (cell 17, 18 and 19).

**Comment by ChickenProp** [comment]
Bar plots use the aesthetic `weight`, not `y`. By default, it has `weight=1`, meaning every row in the dataframe contributes a value of 1 to its relevant bar, i.e. it gives you a count. You want to set `weight='avg(entriesn_daily)'` in cells 13 and 14, and `weight='price'`, `weight='carat'` in 18 and 19.

**Comment by Arn-O** [comment]
I see, now I understand. Thx, that works fine.
