### ISSUE TITLE
geom_bar doesn't sort its fill levels

### ISSUE THREAD

**Issue by ChickenProp** [yhat/ggplot#531]
ggplot(mtcars, aes(x='factor(cyl)', fill='factor(gear)')) + geom_bar()
    ggplot(mtcars, aes(x='factor(cyl)', fill='factor(gear)')) + geom_bar(position='stack')

In both these plots, the ordering of the fill levels is consistent, but unsorted. In the first plot, it goes 4-3-5 (left to right), in the second it goes 4-5-3 (bottom to top). I'd expect both of these to be 3-4-5.

(The stacked one is sorted according to the rgb values of the colors used, and I think the other has to do with the order of the rows in the dataframe.)

Unfortunately, I don't think the geom_bar itself has access to the data it needs to sort properly, at least not in plot().

**Comment by glamp** [comment]
fixed in 3e33d44532cf73e8e739007efc2f141fb563da71
