### ISSUE TITLE
cannot control geom_bar() bar width

### ISSUE THREAD

**Issue by zanemarkson** [yhat/ggplot#547]
It seems that specifying that `geom_bar(position='fill')` will make one unable to control the bar width with `width=` or `binwidth=`

**Comment by glamp** [comment]
`width` now a valid parameter in 52fa6ffa066a287f1490f5670a0d5783dffc3295

**Comment by glamp** [comment]
`binwidth` added in f428e81ecf5a648ccd8c34076689653fe8a2a2f2
