### ISSUE TITLE
stat_smooth get trouble

### ISSUE THREAD

**Issue by nanhuayu** [yhat/ggplot#561]
I'm a new comer to ggplot, and i tried examples in the http://ggplot.yhathq.com/
the graph worked well by ggplot(aes(x='date', y='beef'), data=meat) + geom_line() 
But it went wrong when i tried  stat_smooth(color='blue'), no matter what span value I've changed.
From:nanhuayu
Here is what my graph looks like:
![figure_1](https://cloud.githubusercontent.com/assets/18118017/20145611/b72f1da0-a6db-11e6-9e5b-fc43fdbae956.png)

**Comment by seth-a** [comment]
Same here.  I've tested on ubuntu 14.04, 16.04 and python 2.7 and 3.5 .  Several of the other examples have issues as well.

**Comment by Ezibenroc** [comment]
I have the same issue on Ubuntu 16.04 with Python 3.5 and ggplot installed with `pip3 install --user ggplot`.

Moreover, when I run this example, I get the following warning:
```
/home/tom/.local/lib/python3.5/site-packages/ggplot/stats/stat_smooth.py:77: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  smoothed_data = smoothed_data.sort('x')
```

The warning is easily fixed by changing one line of `stat_smooth.py`, however it does not fix the bug.

**Comment by gepcel** [comment]
You should try `stat_smooth(color=blue, span=0.2, method='lowess')`.
There are three methods of smoothing, I'm guessing at some point, the default method changed from `lowess' to `OLS`, while the doc not.

**Comment by nanhuayu** [comment]
@gepcel 
Really appreciate your answer, and it works!
From 
nanhuayu

**Comment by andysevas** [comment]
Including stat_smooth seems to wreck the datetime values on the x-axis though.  When I run the code with no stat_smooth, it shows a much nicer year format.

**Comment by Guzpenha** [comment]
stat_smooth is still messing with x-axis label

**Comment by heshan007** [comment]
you can use `scale_x_date(labels = date_format("%Y"))` if the year formats are messed up
