### ISSUE TITLE
Incomplete Legends

### ISSUE THREAD

**Issue by zachcp** [yhat/ggplot#94]
Legends do not always contain all of the members  in the legend. Here is an example with built in data where there should be 32 although only eight get plotted. I've tried a couple of examples and the legend seems to max out at eight.  Most use cases won't need 32 but I often have more than eight items in a legend.

```
from ggplot import *
ggplot(aes(x= 'cyl', y='mpg', colour='name'), data=mtcars) + geom_point()
```

**Comment by glamp** [comment]
fixed in 0.9.3
